name: brefrank
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - jupyterlab
      - IPython
      - matplotlib
      # - jax[cuda12_pip]@https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - git+https://github.com/google/brax.git@main
      - flax
      - einops
